import os

from easydict import EasyDict

from utils.enums import PreprocessingType

ROOT_DIR = os.path.dirname(os.path.dirname(__file__))

data_cfg = EasyDict()

# Path to the directory with dataset files
data_cfg.path_to_data = os.path.join(ROOT_DIR, 'data', 'Football Dataset')

# Label mapping
data_cfg.label_mapping = {
    'draw': 0,
    'home': 1,
    'away': 2
}
data_cfg.classes_num = 3

# Categories

data_cfg.categories = {
    'league':   ['La Liga', 
                 'Serie A', 
                 'Premier League', 
                 'Bundesliga', 
                 'UEFA Europa League', 
                 'Ligue 1', 
                 'UEFA Europa Conference League', 
                 'UEFA Champions League'],
                 
    'position': ['Defender', 
                 'Midfielder', 
                 'Forward', 
                 'Goalkeeper'],

    'country':  ['Germany',
                 'France',
                 'Moldova',
                 'Romania',
                 'Serbia',
                 'Italy',
                 'Azerbaijan',
                 'Czech Republic',
                 'Portugal',
                 'Switzerland',
                 'Ukraine',
                 'Kazakhstan',
                 'England',
                 'Belgium',
                 'Spain',
                 'Austria',
                 'Greece',
                 'Turkey',
                 'Bulgaria',
                 'Poland',
                 'Netherlands',
                 'Croatia',
                 'Cyprus',
                 'Wales',
                 'Norway',
                 'Sweden',
                 'Russia',
                 'Israel',
                 'Slovenia',
                 'Denmark',
                 'Scotland',
                 'Hungary',
                ' Slovakia',
                 'Monaco',
                 'Belarus'],
    'referee':  ['David Fernández Borbalan', 'Daniele Orsato', 'Istvan Vad II',
       'Sergiy Boyko', 'Clément Turpin', 'Felix Brych',
       'Pedro Proença Oliveira Alves Garcia', 'Luca Banti',
       'Serge Gumienny', 'Craig Alexander Thomson', 'Björn Kuipers',
       'Antonio Miguel Mateu Lahoz', 'Sergey Karasev', 'Martin Atkinson',
       'Damir Skomina', 'Aleksandar Stavrev', 'Pol van Boekel',
       'Wolfgang Stark', 'Ivan Bebek', 'Felix Zwayer',
       'Alberto Undiano Mallenco', 'Manuel Gräfe', 'Liran Liani',
       'Michael Oliver', 'Anastasios Sidiropoulos', 'Pavel Kralovec',
       'Paolo Tagliavento', 'Ovidiu Hațegan', 'Szymon Marciniak',
       'Cüneyt Çakιr', 'Antony Gautier',
       'Olegário Faustino Manuel Benquerença Bartolo',
       'Aliaksei Kulbakov', 'Mark Clattenburg', 'Viktor Kassai',
       'Gianluca Rocchi', 'Alon Yefet', 'Svein Oddvar Moen',
       'Alexandru Dan Tudor', 'Jonas Eriksson',
       'Manuel Jorge Neves Moreira de Sousa', 'Robert Schörgenhofer',
       'Stefan Johannesson', 'Tom Harald Hagen', 'Nicola Rizzoli',
       'Michael Koukoulakis', 'Ivan Kružliak', 'Bobby Madden',
       'Danny Makkelie', 'Hüseyin Göçek', 'Martin Strömbergsson',
       'Carlos Velasco Carballo', 'Slavko Vinčić', 'Matej Jug',
       'Ruddy Buquet', 'Deniz Aytekin', 'Milorad Mazic', 'William Collum',
       'Artur Manuel Ribeiro Soares Dias', 'Evgen Aranovskiy',
       'Miroslav Zelinka', 'Anthony Taylor', 'Arnold Hunter',
       'Gediminas Mažeika', 'Bas Nijhuis', 'Javier Estrada Fernández',
       'Paweł Raczkowski', 'Vladislav Bezborodov', 'Benoît Bastien',
       'Jesús Gil Manzano', 'Serdar Gözübüyük', 'Tobias Stieler',
       'Jakob Kehlet', 'Istvan Kovacs', 'Carlos Del Cerro Grande',
       'Tamás Bognár', 'Daniel Stefanski', 'Daniel Siebert',
       'Srđan Jovanović', 'Orel Grinfeeld', 'Craig Pawson',
       'Davide Massa', 'Andris Treimanis', 'Georgi Kabakov',
       'Marco Guida', 'Ali Palabiyik', 'Andreas Ekberg',
       'José María Sánchez Martínez', 'Mattias Gestranius', 'Phil Dowd',
       'Andre Marriner', 'Lee Mason', 'Neil Swarbrick', 'Kevin Friend',
       'Howard Webb', 'Jonathan Moss', 'Roger East', 'Mike Jones',
       'Chris Foy', 'Mike Dean', 'Simon Hooper', 'Robert Madley',
       'Stuart Attwell', 'Graham Scott', 'Chris Kavanagh', 'Paul Tierney',
       'Lee Probert', 'Andy Madley', 'David Coote', 'Peter Bankes',
       'Darren England', 'Tim Robinson', 'Robert Jones',
       'Oliver Langford', 'José Luis González González',
       'Miguel Ángel Ayza Gámez', 'Carlos Clos Gómez',
       'Juan Martínez Munuera', 'Alfonso Álvarez Izquierdo',
       'Iñaki Bikandi Garrido', 'Fernando Teixeira Vitienes',
       'Mario Melero López', 'Alejandro José Hernández Hernández',
       'Ricardo De Burgos Bengoetxea', 'Eduardo Prieto Iglesias',
       'Santiago Jaime Latre', 'Ignacio Iglesias Villanueva',
       'David Medié Jiménez', 'José Luis Munuera Montero',
       'Javier Alberola Rojas', 'Daniel Jesús Trujillo Suárez',
       'Pablo González Fuertes', 'Guillermo Cuadra Fernández',
       'Adrián Cordero Vega', 'César Soto Grado',
       'Valentín Pizarro Gómez', 'Jorge Figueroa Vázquez',
       'Isidro Díaz de Mera Escuderos', 'Guido Winkmann', 'Peter Sippel',
       'Tobias Welz', 'Knut Kircher', 'Florian Meyer', 'Michael Weiner',
       'Günter Perl', 'Peter Gagelmann', 'Jochen Drees',
       'Robert Hartmann', 'Thorsten Kinhöfer', 'Christian Dingert',
       'Bastian Dankert', 'Marco Fritz', 'Sascha Stegemann',
       'Benjamin Brand', 'Patrick Ittrich', 'Harm Osmers',
       'Markus Schmidt', 'Robert Kampka', 'Frank Willenborg',
       'Sven Jablonski', 'Bibiana Steinhaus', 'Sören Storks',
       'Martin Petersen', 'Benjamin Cortus', 'Robert Schröder',
       'Daniel Schlager', 'Florian Badstübner', 'Matthias Jöllenbeck',
       'Tobias Reichel', 'Piero Giacomelli', 'Michael Fabbri',
       'Fabio Maresca', 'Claudio Gavillucci', 'Paolo Valeri',
       'Gianluca Manganiello', 'Gianluca Aureliano', 'Rosario Abisso',
       'Antonio Damato', 'Giampaolo Calvarese', 'Fabrizio Pasqua',
       'Daniele Doveri', 'Paolo Silvio Mazzoleni', 'Riccardo Pinzani',
       'Davide Ghersini', 'Luca Pairetto', 'Daniele Chiffi',
       'Marco Di Bello', 'Maurizio Mariani', 'Luigi Nasca',
       'Massimiliano Irrati', 'Antonio Giua', 'Eugenio Abbattista',
       'Ivano Pezzuto', 'Federico La Penna', 'Francesco Fourneau',
       'Juan Luca Sacchi', 'Marco Serra', 'Marco Piccinini',
       'Lorenzo Maggioni', 'Antonio Di Martino', 'Livio Marinelli',
       'Manuel Volpi', 'Luca Massimi', 'Aleandro Di Paolo',
       'Federico Dionisi', 'Riccardo Ros', 'Alessandro Prontera',
       'Simone Sozza', 'Daniel Amabile', 'Giovanni Ayroldi',
       'Valerio Marini', 'Alberto Santoro', 'Antonio Rapuano',
       'Matteo Gariglio', 'Matteo Marchetti', 'Daniele Paterna',
       'Francesco Meraviglia', 'Giacomo Camplone', 'Amaury Delerue',
       'Mikael Lesage', 'Thomas Léonard', 'Jérôme Brisard',
       'Benoît Millot', 'Johan Hamel', 'Karim Abed', 'Sébastien Desiage',
       'Stéphane Jochem', 'Hakim Ben El Hadj', 'Olivier Thual',
       'Sébastien Moreira', 'Frank Schneider', 'François Letexier',
       'Tony Chapron', 'Nicolas Rainville', 'Jérôme Miguelgorry',
       'Stephan Klossner', 'Sandro Schärer', 'Stéphanie Frappart',
       'Eric Wattellier', 'Jeremy Stinat', 'Florent Batta',
       'Willy Delajod', 'Alain Bieri', 'Jérémie Pignard',
       'Anthony Ustaritz', 'Aurélien Petit', 'Bastien Dechepy']
}

# Training configuration
data_cfg.preprocess_type = PreprocessingType.standardization
# data_cfg.preprocess_type = PreprocessingType.normalization
